name: Test Builds

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}

env:
  REGISTRY: ghcr.io
  OWNER: ndigitals
  PACKAGE: wp-dev-container
  ACTION_VERSION: 1

jobs:
  build:
    name: Build Images

    strategy:
      fail-fast: false
      matrix: 
        PHP_VERSION:
          - '8.0'
          - '8.3'
        NODE_VERSION:
          - '16'
          - '20'
        builder:
          - ubuntu-22.04
          - self-hosted
        platform:
          - amd64
          - arm64
        exclude:
          - builder: ubuntu-22.04
            platform: arm64
          - builder: self-hosted
            platform: amd64

    runs-on:
      - ${{ matrix.builder }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags

      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/marketplace/actions/docker-login
      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      # https://github.com/marketplace/actions/setup-node-js-environment
      - name: Setup Node Environment
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      # https://github.com/marketplace/actions/dev-container-build-and-run-action
      - name: Pre-build Dev Container Image
        uses: devcontainers/ci@v0.3
        env:
          # see: https://github.com/devcontainers/ci/issues/191#issuecomment-1603857155
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
          PHP_VERSION: ${{ matrix.PHP_VERSION }}
          NODE_VERSION: ${{ matrix.NODE_VERSION }}
        with:
          platform: linux/${{ matrix.platform }}
          imageName: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.PACKAGE }}
          cacheFrom: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.PACKAGE }}
          imageTag: php-${{ matrix.PHP_VERSION }}-node-${{ matrix.NODE_VERSION }}
          push: never
          skipContainerUserIdUpdate: true

      - name: Test Copying Container Image Archive
        run: |
            rm -f /tmp/php-${{ matrix.PHP_VERSION }}-node-${{ matrix.NODE_VERSION }}-oci.tar
            mv /tmp/output.tar /tmp/php-${{ matrix.PHP_VERSION }}-node-${{ matrix.NODE_VERSION }}-oci.tar

      # https://github.com/marketplace/actions/upload-a-build-artifact
      - name: Upload Digests
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE }}-php-${{ matrix.PHP_VERSION }}-node-${{ matrix.NODE_VERSION }}-${{ matrix.platform }}
          path: /tmp/php-${{ matrix.PHP_VERSION }}-node-${{ matrix.NODE_VERSION }}-oci.tar
          if-no-files-found: error
          retention-days: 1

  download:
    name: Test Download Images
    needs: build
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix: 
        PHP_VERSION:
          - '8.0'
          - '8.3'
        NODE_VERSION:
          - '16'
          - '20'

    runs-on: ubuntu-latest

    concurrency:
      group: ${{ matrix.PHP_VERSION }}-${{ matrix.NODE_VERSION }}-${{ matrix.platform }}

    steps:
      # https://github.com/marketplace/actions/download-a-build-artifact
      - name: Download Digests - amd64
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.PACKAGE }}-php-${{ matrix.PHP_VERSION }}-node-${{ matrix.NODE_VERSION }}-amd64
          path: /tmp/${{ env.PACKAGE }}/amd64/${{ env.PACKAGE }}-php-${{ matrix.PHP_VERSION }}-node-${{ matrix.NODE_VERSION }}-oci.tar

      # https://github.com/marketplace/actions/download-a-build-artifact
      - name: Download Digests - arm64
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.PACKAGE }}-php-${{ matrix.PHP_VERSION }}-node-${{ matrix.NODE_VERSION }}-arm64
          path: /tmp/${{ env.PACKAGE }}/arm64/${{ env.PACKAGE }}-php-${{ matrix.PHP_VERSION }}-node-${{ matrix.NODE_VERSION }}-oci.tar

      - name: List Artifact Downloads
        run: ls -R
        working-directory: /tmp/${{ env.PACKAGE }}

